# Handpicked colors for constructors
constructor_colors = {
    'Red Bull': 'navy',
    'Mercedes': 'cyan',
    'Ferrari': 'red',
    'Alfa Romeo': 'darkred',
    'AlphaTauri': 'lightslategrey',
    'Williams': 'lightskyblue',
    'McLaren': 'orange',
    'Aston Martin': 'green',
    'Alpine F1 Team': 'dodgerblue',
    'Haas F1 Team': 'silver',
    'Renault': 'gold',
    'Toro Rosso': 'darkgrey',
    'Force India': 'pink',
    'Sauber': 'darkgoldenrod',
    'Manor Marussia': 'grey',
    'Benetton': 'dodgerblue',
    'Jordan': 'yellow',
    'Jaguar': 'green',
    'Ligier': 'darkblue',
    'Footwork': 'chocolate',
    'Prost': 'blueviolet',
    'Stewart': 'snow',
    'BAR': 'lightgray',
    'Honda': 'gainsboro',
    'BMW Sauber': 'powderblue',
    'Toyota': 'tomato',
    'Brawn': 'lawngreen'
    }